-- Supabase SQL Editor에서 실행하세요.
-- public.messages 테이블 생성 + Row Level Security + 읽기/등록 정책

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Anyone can read messages" on public.messages;
create policy "Anyone can read messages"
on public.messages
for select
to anon
using (true);

drop policy if exists "Anyone can insert valid messages" on public.messages;
create policy "Anyone can insert valid messages"
on public.messages
for insert
to anon
with check (
  char_length(name) between 1 and 30
  and char_length(content) between 1 and 300
);
